version: '3.8'
services:
  detectron2_layoutparser:
    image: nvidia/cuda:11.1.1-cudnn8-devel-ubuntu18.04
    container_name: detectron2_layoutparser
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - FORCE_CUDA=1
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    command: >
      /bin/bash -c "apt-get update --fix-missing && apt-get install -y python3-pip python3-dev &&
      pip3 install torch==1.10 torchvision==0.11.1 -f https://download.pytorch.org/whl/cu111/torch_stable.html &&
      pip3 install git+https://github.com/facebookresearch/detectron2 &&
      pip3 install layoutparser[layoutmodels] pymupdf &&
      tail -f /dev/null"
